### ISSUE TITLE
Create a register now button and page

### ISSUE THREAD

**Issue by surajcm** [surajcm/Poseidon#44]
On the login screen, there should be a clickable text that says create a new account. Once the user clicks on it, it should redirect to a page for account creation.

No need to do the save part, the page should request the users with a basic user creation view.

**Comment by dinesh-07** [comment]
Shall I work on this? assign to me

**Comment by surajcm** [comment]
sure

**Comment by gunawan043** [comment]
can you give me this assignment?

**Comment by surajcm** [comment]
if @dinesh-07 is not intending to work on it, then probably it is fine.

**Comment by surajcm** [comment]
I implemented this, and it is working fine
