### ISSUE TITLE
Model search drop down - disable it by default, enable only when make is selected

### ISSUE THREAD

**Issue by surajcm** [surajcm/Poseidon#8]
Model search drop-down (on transactions, model search fields, add / edit transaction pages) - disable it by default, enable only when the make is selected

**Comment by sijinpavithran** [comment]
Hi Suraj,
I would like to work on this issue.

**Comment by surajcm** [comment]
Thanks a lot for showing interest to contribute !!!

Please go ahead and fork the repo, and create a PR. Please feel free to ask questions, if you have any.

**Comment by sijinpavithran** [comment]
Thanks.
Just to clarify, I have to disable "Model" dropdown by default on the following pages?

1. Transactions page --> Search Transactions section (http://localhost:8181/txs/List.htm)
2. Add New Transaction Form page (http://localhost:8181/txs/AddTxn.htm)
3. Edit Transaction Form page (http://localhost:8181/txs/EditTxn.htm)

Please let me know if my understanding is correct?

**Comment by surajcm** [comment]
Yes, you are right, it is on these 3 pages only.

**Comment by sijinpavithran** [comment]
Hi, I have raised a PR. Please review and let me know if any issue. Thanks

**Comment by surajcm** [comment]
Sure, I just reviewed it. It looks good. Thanks a lot for contributing. I will merge it now

**Comment by sijinpavithran** [comment]
Thanks Suraj. Please let me know if you planning any feature enhancement and need a hand. I am happy to contribute to this or any other projects.

**Comment by surajcm** [comment]
Thank you for showing interest. I do have plans for future enhancements, I will definitely reach out / open a ticket once I have finalized the design of new features.
