### ISSUE TITLE
Transaction edit screen - dont show the customer id, also limit the customer info to show there

### ISSUE THREAD

**Issue by surajcm** [surajcm/Poseidon#9]
Transaction edit screen - don't show the customer id on the screen, just the edit customer button is enough. Also, limit the customer info to show there

**Comment by sudarshan-d-s** [comment]
Hello,
I would like to work on this issue. But i would require some more clarification.

What I understand:
- The label 'Customer Id:' along with input box (where Customer Id is being populated), needs to be removed. Only the button cell 'Edit Customer Details' should remain in that table row.

Clarification required:
- Which of the customer info needs to be retained/removed (I see details such as "Name", "Address", "Phone", "Mobile", "Email" etc).

Let me know how to proceed.

**Comment by surajcm** [comment]
Thanks a lot for showing interest to contribute !!!

We would like to have only the name and email to be shown on the `Transaction Edit screen`

Please feel free to create a PR.

**Comment by sudarshan-d-s** [comment]
Hi,

Please find the attached the Edit Transaction screenshot.

![Edit_Transaction_Screen](https://user-images.githubusercontent.com/24407462/116405952-d7b76280-a84d-11eb-80d5-fcbdabf8d398.png)

1. I was successful in removing the Customer Info Fields 'Customer Id', 'Address', 'Phone', 'Mobile' from the Transaction Screen.
    - For now, this is done by editing just the jsp.
    -  Do i need to exclude this info from the Object 'TransactionForm'(Encapsulated in ModelAndView) object as well?

2. I am still unclear on if these are the only fields that need to be removed.
   - Please let me know which fields need to be removed/retained among box 1 and 2 (Highlighted in the attached image).

**Comment by surajcm** [comment]
Hi @sudarshan-d-s ,

Thanks for sharing the screenshot, please find my comments below.
1. We are fine with just the jsp change itself. However, it would be better if the `Edit customer details` button is on the same row (immediately following the email text field).
2. We still require the data on box 1 & 2

**Comment by sudarshan-d-s** [comment]
Alright @surajcm 

I'll do the changes and share the screenshot. Then if the changes are as required, i'll raise the PR.

**Comment by sudarshan-d-s** [comment]
Hi @surajcm ,

Please find the image below and let me know if you're fine with the changes.

![Screenshot 2021-04-29 at 12 47 09 PM](https://user-images.githubusercontent.com/24407462/116515217-9b394480-a8e9-11eb-8b05-dddd735d6076.png)

**Comment by surajcm** [comment]
Hi @sudarshan-d-s ,

Yes, this looks good, please proceed with the PR.

**Comment by sudarshan-d-s** [comment]
Hi,

I have raised the PR. 

Could you link the PR to this issue, and assign the issue to me?

Thank You.

**Comment by surajcm** [comment]
Sure, I have assigned the issue to you and lined the PR. I will review the PR soon and will merge it.

Thank you for your contribution.

**Comment by sudarshan-d-s** [comment]
@surajcm 

Thank You for the Opportunity.

I think the issue has not been assigned to me yet. The Assignee Field is empty.

**Comment by surajcm** [comment]
My bad. I just assigned it to you now.
